import plantarTreatment1 from "../../../public/plantar/plantarTreatment1.webp";
import plantarTreatment2 from "../../../public/plantar/plantarTreatment2.webp";
import plantarTreatment3 from "../../../public/plantar/plantarTreatment3.webp";
import neuropatheticTesti1 from "../../../public/gout/neuropatheticTesti1.webp";
import neuropatheticTesti2 from "../../../public/gout/neuropatheticTesti2.webp";
import neuropatheticTesti3 from "../../../public/gout/neuropatheticTesti3.webp";
import treatment1 from "../../../public/gout/goutTreatmentImg.webp";
import { Review, Treatment, TreatmentData, faqData } from "./allTypes";
import starImg from "../../../public/desktop/Stars.webp";
import fiveStar from "../../../public/desktop/5Stars.webp";

export const neuropatheticTreatmentAtNivan: TreatmentData[] = [
  {
    id: 1,
    name: "Radiofrequency Ablation (RFA)",
    img: plantarTreatment1,
    process:
      "Heat generated by radio waves targets pain-causing nerves, blocking pain signals to the brain.",
    benefits: [
      "Long-lasting pain relief",
      "Minimally invasive procedure",
      "Performed under local anesthesia"
    ],
  },
  {
    id: 2,
    name: "Medicine Management",
    img: plantarTreatment2,
    process:
      "Tailored medications prescribed to manage inflammation and pain effectively.",
    benefits: [
      "Immediate relief from discomfort",
      "Improves quality of life"
    ],
  }
];

export const neuropatheticHeading: Treatment = {
  heading: "Neuropathic Pain Treatments at Nivaan",
  para: "We use the most advanced, scientifically proven technologies to ensure pain relief",
};

export const neuropatheticPatientReviewData: Review[] = [
    {
      id: 1,
      name: "Abhjeet Banerjee",
      reviewText:
        "“I struggled with severe neuropathic pain for years. After RFA at Nivaan, I’m finally pain-free. Thank you, Nivaan!”",
      postedWhen: "2 weeks ago",
      img: neuropatheticTesti1,
      starImg: starImg,
    },
    {
      id: 2,
      name: "Sneha Verma",
      reviewText:
        "“Nivaan’s personalized approach, including medication and therapy, has transformed my life. Highly recommend their care!”",
      postedWhen: "5 weeks ago",
      img: neuropatheticTesti2,
      starImg: fiveStar,
    },
    {
      id: 3,
      name: "Arun Mehta",
      reviewText:
        "“The RFA procedure was quick and almost painless. My neuropathic pain is gone, and I feel likemyself again.”",
      postedWhen: "7 weeks ago",
      img: neuropatheticTesti3,
      starImg: fiveStar,
    },
];

export const neuropathicFaqData: faqData[] = [
    {
      title: "What is Neuropathic Pain?",
      desc: "Neuropathic pain occurs when nerves are damaged or malfunction, leading to chronic pain, burning sensations, or tingling.",
    },
    {
      title: "What causes Neuropathic Pain?",
      desc: "Common causes include:\n• Diabetes (diabetic neuropathy)\n• Spinal injuries\n• Nerve compression\n• Infections like shingles",
    },
    {
      title: "Who treats Neuropathic Pain at Nivaan?",
      desc: "A dedicated team of pain specialists, physiotherapists, and care managers collaborate to create personalized treatment plans.",
    },
    {
      title: "How can Neuropathic Pain be relieved quickly?",
      desc: "Radiofrequency Ablation (RFA) and medicine management are the most effective options for immediate and long-lasting relief.",
    },
    {
      title: "What are the benefits of RFA?",
      desc: "• Non-surgical, minimally invasive\n• Quick recovery time\n• Long-term relief from nerve-related pain",
    },
    {
      title: "How long does the RFA procedure take?",
      desc: "RFA is an outpatient procedure completed in 30–40 minutes.",
    },
    {
      title: "Is insurance accepted?",
      desc: "Yes, most treatments are covered by insurance, and Nivaan offers full insurance support.",
    },
    {
      title: "When can I return to work?",
      desc: "Most patients return to work the next day, with light activity for a few days as advised by the doctor.",
    },
  ];