import plantarTreatment1 from "../../../public/plantar/plantarTreatment1.webp";
import plantarTreatment2 from "../../../public/plantar/plantarTreatment2.webp";
import plantarTreatment3 from "../../../public/plantar/plantarTreatment3.webp";
import plantarTesti1 from "../../../public/plantar/plantarTestimonial1.webp";
import plantarTesti2 from "../../../public/plantar/plantarTestimonial2.webp";
import plantarTesti3 from "../../../public/plantar/plantarTestimonial3.webp";
import treatment1 from "../../../public/gout/goutTreatmentImg.webp";
import { Review, Treatment, TreatmentData, faqData } from "./allTypes";
import starImg from "../../../public/desktop/Stars.webp";
import fiveStar from "../../../public/desktop/5Stars.webp";

export const plantarTreatmentAtNivan: TreatmentData[] = [
  {
    id: 1,
    name: "Radiofrequency Ablation (RFA)",
    img: plantarTreatment1,
    process:
      "Heat generated by radio waves targets pain-causing nerves, providing lasting relief.",
    benefits: [
      "Minimally invasive",
      "Performed under local anesthesia",
      "Long-term pain relief"
    ],
  },
  {
    id: 2,
    name: "Medicine Management",
    img: plantarTreatment2,
    process:
      "Tailored medications prescribed to manage inflammation and pain effectively.",
    benefits: [
      "Immediate relief from discomfort",
      "Improves quality of life"
    ],
  },
  {
    id: 3,
    name: "Intra-Articular Steroid Injection",
    img: plantarTreatment3,
    process:
      "Steroid injection into the joint reduces inflammation and relieves pain.",
    benefits: [
      "Immediate pain relief",
      "Restores joint mobility",
      "Quick outpatient procedure"
    ],
  }
];

export const plantarHeading: Treatment = {
  heading: "Plantar Fasciitis Treatments at Nivaan",
  para: "We use the most advanced, scientifically proven technologies to ensure pain relief",
};

export const plantarPatientReviewData: Review[] = [
    {
      id: 1,
      name: "Amit Malhotra",
      reviewText:
        "“After struggling with plantar fasciitis for months, Nivaan’s therapy worked wonders. My painis gone, and I can walk without discomfort!”",
      postedWhen: "2 weeks ago",
      img: plantarTesti1,
      starImg: starImg,
    },
    {
      id: 2,
      name: "Ritu Sharma",
      reviewText:
        "“I opted for RFA at Nivaan, and it was the best decision ever. A quick procedure, and now I’m pain-free. Highly recommended!”",
      postedWhen: "5 weeks ago",
      img: plantarTesti2,
      starImg: fiveStar,
    },
    {
      id: 3,
      name: "Pankaj Verma",
      reviewText:
        "“The team at Nivaan is amazing! Their personalized treatment, including medicine management, gave me instant relief fromplantar fasciitis.”",
      postedWhen: "7 weeks ago",
      img: plantarTesti3,
      starImg: fiveStar,
    },
];

export const plantarFaqData: faqData[] = [
  {
    title: "What is Plantar Fasciitis?",
    desc: "Plantar fasciitis is a common foot condition where the tissue connecting your heel to your toes becomes inflamed, causing sharp heel pain, especially in the morning or after long periods of rest.",
  },
  {
    title: "What causes Plantar Fasciitis?",
    desc: "Common causes include:\n• Overuse or strain on the plantar fascia\n• Flat feet or high arches\n• Obesity or sudden weight gain\n• Prolonged standing or walking",
  },
  {
    title: "Who treats Plantar Fasciitis at Nivaan?",
    desc: "A dedicated team of pain specialists, physiotherapists, and care managers collaborate to create personalized treatment plans.",
  },
  {
    title: "How can Plantar Fasciitis pain be relieved quickly?",
    desc: "Radiofrequency Ablation (RFA) and medication management are effective solutions for both immediate and long-term pain relief.",
  },
  {
    title: "What are the benefits of these treatments?",
    desc: "• Minimally invasive, non-surgical options\n• Quick recovery time\n• Performed by experienced specialists",
  },
  {
    title: "How long does the procedure take?",
    desc: "Most procedures, like RFA or PRP, are completed in 30–40 minutes as outpatient treatments.",
  },
  {
    title: "Is insurance accepted?",
    desc: "Yes, most treatments are covered by insurance, and Nivaan provides full insurance support.",
  },
  {
    title: "When can I return to work?",
    desc: "Patients can typically resume work the next day, with light activity as advised for a few days.",
  },
];